name: 🐛 Bug Report / Сообщение об ошибке
description: Report an issue with RPG Loot / Сообщите об ошибке в RPG Loot
title: "[🐛] "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report / Сообщение об ошибке

        Please describe the issue as clearly as possible. / Пожалуйста, опишите проблему как можно подробнее.

  - type: dropdown
    id: version
    attributes:
      label: Minecraft Version / Версия Minecraft
      options:
        - 1.20.1
        - 1.21.1
      description: Which Minecraft version are you using the datapack with? / Для какой версии Minecraft используется набор данных?
    validations:
      required: true

  - type: checkbox
    id: latest_version
    attributes:
      label: Are you using the latest version? / Используете ли вы последнюю версию?
      description: Check this box if you're using the latest available version of RPG Loot / Отметьте, если вы используете последнюю доступную версию RPG Loot
      options:
        - label: I'm using the latest version / Я использую последнюю версию

  - type: textarea
    id: description
    attributes:
      label: Description / Описание
      description: What happened? / Что произошло?
      placeholder: "Describe the bug / Опишите ошибку"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce / Шаги воспроизведения
      description: How can we reproduce the bug? / Как воспроизвести ошибку?
      placeholder: |
        1. Install the datapack / Установить набор данных
        2. Kill a mob X / Убить моба X
        3. Nothing drops / Ничего не выпадает
    validations:
      required: false
