blank_issues_enabled: true
issue_templates:
  - name: ⚠️ Bug Report / Сообщение об ошибке
    description: Report an issue with RPG Loot / Сообщите об ошибке в RPG Loot
    file: bug-report.yml
  - name: 💡 Content Suggestion / Предложение о контенте
    description: Suggest an feature to add / Предложите функцию для добавления
    file: content-suggestion.yml
  - name: ⚙ Config Tweak / Предложение настройки
    description: Request a tweak to loot balance or rarity / Предложите изменить баланс или редкость добычи
    file: setting-request.yml
